[build]
builder = "NIXPACKS"

[phases.setup]
nixPkgs = ["nodejs_22"]

[phases.install]
cmds = ["rm -f package-lock.json", "npm install"]

[phases.build]
cmds = ["npm run build"]

[deploy]
startCommand = "npx serve dist -s -l $PORT"

[variables]
NIXPACKS_NODE_VERSION = "22"
